### ISSUE TITLE
Unable to set Name of ebs_volume

### ISSUE THREAD

**Issue by kohenkatz** [chef-cookbooks/aws#116]
EBS Volumes in the AWS Console have a "name" attribute, but the ebs_volume resource doesn't allow it to be set.  This makes it hard ot keep track of the volumes in our account.

The "name" attribute should be added to the ebs_volume resource.

**Comment by jorhett** [comment]
You tag it with resource_tag the volume_id, as documented with an example even ;)

**Comment by dreamnite** [comment]
And how do we determine the id of the volume we just created? I have a volume I created with aws_ebs_volume  and would like it to have a friendly name tag, but I can't assign it without knowing the volume id I just created. 

It's a chicken and egg issue.

**Comment by kohenkatz** [comment]
@dreamnite after the volume is created, the volume ID is set back in the configuration. See https://github.com/chef-cookbooks/aws/blob/master/providers/ebs_volume.rb#L46

You can then read it from `node['aws']['ebs_volume'][new_resource.name]['volume_id']`.

However, note that the volume ID will only be persisted in your configuration if you are running Chef Server.  If you are running Chef Solo, the volume ID will be forgotten as soon as Chef finishes running.
