### ISSUE TITLE
using s3_file on NON ec2 instances... 

### ISSUE THREAD

**Issue by joshzitting** [chef-cookbooks/aws#120]
I keep getting an error and I have looked around and cant see what I am doing wrong... 
Here is my resource...
```
include_recipe "aws"

aws_s3_file "/tmp/file_I_want.tar.gz" do
  bucket "config-files"
  remote_path "file_I_want.tar.gz"
  aws_access_key_id node["aws-key-id"]
  aws_secret_access_key node["aws-secret"]
end
```

```
         * aws_s3_file[/tmp/file_I_want.tar.gz] action create

           ================================================================================
           Error executing action `create` on resource 'aws_s3_file[/tmp/file_I_want.tar.gz]'
           ================================================================================

           Errno::ETIMEDOUT
           ----------------
           Connection timed out - connect(2) for "169.254.169.254" port 80

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/aws/libraries/ec2.rb:83:in `query_instance_availability_zone'
           /tmp/kitchen/cache/cookbooks/aws/libraries/ec2.rb:51:in `instance_availability_zone'
           /tmp/kitchen/cache/cookbooks/aws/libraries/ec2.rb:63:in `create_aws_interface'
           /tmp/kitchen/cache/cookbooks/aws/libraries/s3.rb:9:in `s3'
           /tmp/kitchen/cache/cookbooks/aws/providers/s3_file.rb:33:in `do_s3_file'
           /tmp/kitchen/cache/cookbooks/aws/providers/s3_file.rb:9:in `block in class_from_file'

           Resource Declaration:
```

**Comment by joshzitting** [comment]
sorry...
Chef: 12.2.0
root@29066834:~# /opt/chef/embedded/bin/ruby --version
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]

on Ubuntu 14.04.2 LTS 
Using test kitchen... 
Thanks!!!

**Comment by joshzitting** [comment]
I destroyed the machine and re ran the recipe and I am now getting a 404 Not Found error....

**Comment by ubiquitousthey** [comment]
Is this on an ec2 instance?

**Comment by joshzitting** [comment]
no it is  on a joyent ubuntu instance.. 
does it have to be on an ec2 instance??

**Comment by joshzitting** [comment]
Anyone have any ideas or suggestions on this?

**Comment by joshzitting** [comment]
so with some very welcome help from Euphy on IRC we were able to get a workaround... but I would like to see a more permanent solution.. 
the solution was in libraries/ec2.rb line 51 to set the availabillity zone before it tries to query for the zone.. 

```
      def instance_availability_zone
        @@instance_availability_zone = "us-west-2-"
        @@instance_availability_zone ||= query_instance_availability_zone
      end
```

The extra "-" after the zone is needed for this snippet around line 64ish

```
        region = instance_availability_zone
        region = region[0, region.length - 1]
```

I have tried setting this in the attributes (default[:aws][:availabillity_zone]) instead of modifying this file but it does not work!!! 

Can some one either fix this issue so that it can be overridden or point me in the right direction to doing so?

I would like to be able to pull s3 files from s3 and store/use them on non-ec2 machines. 
Thanks!!! 
Josh

**Comment by fletchowns** [comment]
I was going crazy trying to figure out why this wasn't working, glad to hear that it wasn't just me!

**Comment by ubiquitousthey** [comment]
I just updated PR#115 to fix this.

**Comment by TaopaiC** [comment]
I have s3 files on cn-north-1 and us-east-1 , so I've had to use different region attributes and aws credentials in `aws_s3_file` .

I tried to add region attribute to aws_s3_file in PR #149 .

**Comment by tas50** [comment]
This should be fixed by the inclusion of the region attribute.  You can set that attribute and avoid this problem.

**Comment by sulaimanismail** [comment]
I'm not able to download to windows ec2 instance following installer from s3, can anyone please help me.
Cookbook version
8.0.3

Chef-client version
[13.0]

'windows', '~> 4.2.5'
 'java_se', '~> 11.0'

configure.rb
installation_media_folder = 'C:/InstallationMedia'
directory installation_media_folder do
  rights :full_control, 'Administrator'
  action :create
end

files_to_copy = ['TableauServer-64bit.exe', 'TableauServerWorker-64bit.exe']

files_to_copy.each do |installer|
  aws_s3_file "#{installation_media_folder}/#{installer}" do
    bucket 'test-DEV'
    remote_path "version/10.5.3/#{installer}"
    region 'us-east-1'
    action :create
  end
end

### Actual Result:
17:51:53 * directory[C:/InstallationMedia] action create
17:51:53 - create new directory C:/InstallationMedia
17:51:53 - change dacl
17:51:53 * aws_s3_file[C:/InstallationMedia/TableauServer-64bit.exe] action create
17:51:53 * remote_file[C:/InstallationMedia/TableauServer-64bit.exe] action create
17:51:53  
17:51:53  
17:51:53 ================================================================================
17:51:53 Error executing action `create` on resource 'remote_file[C:/InstallationMedia/TableauServer-64bit.exe]'
17:51:53 ================================================================================
17:51:53  
17:51:53 Net::HTTPServerException
17:51:53 ------------------------
17:51:53 403 "Forbidden"
17:51:53  
17:51:53 Resource Declaration:
17:51:53 ---------------------
17:51:53 # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/aws/resources/s3_file.rb
17:51:53  
17:51:53 149: remote_file new_resource.name do
17:51:53 150: path new_resource.path
17:51:53 151: source s3_url
17:51:53 152: owner new_resource.owner if new_resource.owner
17:51:53 153: group new_resource.group if new_resource.group
17:51:53 154: mode new_resource.mode if new_resource.mode
17:51:53 155: checksum new_resource.checksum if new_resource.checksum
17:51:53 156: backup new_resource.backup
17:51:53 157: headers new_resource.headers if new_resource.headers
17:51:53 158: use_etag new_resource.use_etag
17:51:53 159: use_last_modified new_resource.use_last_modified
17:51:54 160: atomic_update new_resource.atomic_update
17:51:54 161: force_unlink new_resource.force_unlink
17:51:54 162: manage_symlink_source new_resource.manage_symlink_source
17:51:54 163: sensitive new_resource.sensitive
17:51:54 164: retries new_resource.retries
17:51:54 165: retry_delay new_resource.retry_delay
17:51:54 166: if node['platform_family'] == 'windows'
17:51:54 167: inherits new_resource.inherits
17:51:54 168: rights new_resource.rights
17:51:54 169: end
17:51:54 170: action resource_action
17:51:54  
17:51:54 Compiled Resource:
17:51:54 ------------------
17:51:54 # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/aws/resources/s3_file.rb:149:in `do_s3_file'
17:51:54  
17:51:54 remote_file("C:/InstallationMedia/TableauServer-64bit.exe") do
17:51:54 provider Chef::Provider::RemoteFile
17:51:54 action [:create]
17:51:54 default_guard_interpreter :default
17:51:54 use_etag true
17:51:54 use_last_modified true
17:51:54 cookbook_name "image-win-tableau-master"
17:51:54 checksum nil
17:51:54 backup 5
17:51:54 path "C:/InstallationMedia/TableauServer-64bit.exe"
17:51:54 verifications []
17:51:54 rights nil
17:51:54 deny_rights nil
17:51:54 inherits true
17:51:54 declared_type :remote_file
17:51:54 atomic_update true
17:51:54 retries 0
17:51:54 retry_delay 2
17:51:54 not_if { #code block }
17:51:54 end
17:51:54  
17:51:54 System Info:
17:51:54 ------------
17:51:54 chef_version=13.0.118
17:51:54 platform=windows
17:51:54 platform_version=6.3.9600
17:51:54 ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
17:51:54 program_name=C:/opscode/chef/bin/chef-solo
17:51:54 executable=C:/opscode/chef/bin/chef-solo
17:51:54  
17:51:54  
17:51:54 ================================================================================
17:51:54 Error executing action `create` on resource 'aws_s3_file[C:/InstallationMedia/TableauServer-64bit.exe]'
17:51:54 ================================================================================
17:51:54  
17:51:54 Net::HTTPServerException
17:51:54 ------------------------
17:51:54 remote_file[C:/InstallationMedia/TableauServer-64bit.exe] (C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/aws/resources/s3_file.rb line 149) had an error: Net::HTTPServerException: 403 "Forbidden"
17:51:54  
17:51:54 Resource Declaration:
17:51:54 ---------------------

**Comment by ubiquitousthey** [comment]
I suspect you aren’t using the credentials you think you are or your iam
role or user policy  isn’t set right.

**Comment by majormoses** [comment]
> I'm not able to download to windows ec2 instance following installer from s3, can anyone please help me.
> Cookbook version
> 8.0.3
> 
> Chef-client version
> [13.0]
> 
> 'windows', '> 4.2.5'
> 'java_se', '> 11.0'
> 
> configure.rb
> installation_media_folder = 'C:/InstallationMedia'
> directory installation_media_folder do
> rights :full_control, 'Administrator'
> action :create
> end
> 
> files_to_copy = ['TableauServer-64bit.exe', 'TableauServerWorker-64bit.exe']
> 
> files_to_copy.each do |installer|
> aws_s3_file "#{installation_media_folder}/#{installer}" do
> bucket 'test-DEV'
> remote_path "version/10.5.3/#{installer}"
> region 'us-east-1'
> action :create
> end
> end
> 
> ### Actual Result:
> 17:51:53 * directory[C:/InstallationMedia] action create
> 17:51:53 - create new directory C:/InstallationMedia
> 17:51:53 - change dacl
> 17:51:53 * aws_s3_file[C:/InstallationMedia/TableauServer-64bit.exe] action create
> 17:51:53 * remote_file[C:/InstallationMedia/TableauServer-64bit.exe] action create
> 17:51:53
> 17:51:53
> 17:51:53 ================================================================================
> 17:51:53 Error executing action `create` on resource 'remote_file[C:/InstallationMedia/TableauServer-64bit.exe]'
> 17:51:53 ================================================================================
> 17:51:53
> 17:51:53 Net::HTTPServerException
> 17:51:53 ------------------------
> 17:51:53 403 "Forbidden"
> 17:51:53
> 17:51:53 Resource Declaration:
> 17:51:53 ---------------------
> 17:51:53 # In C:/Users/ADMINI1/AppData/Local/Temp/kitchen/cache/cookbooks/aws/resources/s3_file.rb
> 17:51:53
> 17:51:53 149: remote_file new_resource.name do
> 17:51:53 150: path new_resource.path
> 17:51:53 151: source s3_url
> 17:51:53 152: owner new_resource.owner if new_resource.owner
> 17:51:53 153: group new_resource.group if new_resource.group
> 17:51:53 154: mode new_resource.mode if new_resource.mode
> 17:51:53 155: checksum new_resource.checksum if new_resource.checksum
> 17:51:53 156: backup new_resource.backup
> 17:51:53 157: headers new_resource.headers if new_resource.headers
> 17:51:53 158: use_etag new_resource.use_etag
> 17:51:53 159: use_last_modified new_resource.use_last_modified
> 17:51:54 160: atomic_update new_resource.atomic_update
> 17:51:54 161: force_unlink new_resource.force_unlink
> 17:51:54 162: manage_symlink_source new_resource.manage_symlink_source
> 17:51:54 163: sensitive new_resource.sensitive
> 17:51:54 164: retries new_resource.retries
> 17:51:54 165: retry_delay new_resource.retry_delay
> 17:51:54 166: if node['platform_family'] == 'windows'
> 17:51:54 167: inherits new_resource.inherits
> 17:51:54 168: rights new_resource.rights
> 17:51:54 169: end
> 17:51:54 170: action resource_action
> 17:51:54
> 17:51:54 Compiled Resource:
> 17:51:54 ------------------
> 17:51:54 # Declared in C:/Users/ADMINI1/AppData/Local/Temp/kitchen/cache/cookbooks/aws/resources/s3_file.rb:149:in `do_s3_file' 17:51:54 17:51:54 remote_file("C:/InstallationMedia/TableauServer-64bit.exe") do 17:51:54 provider Chef::Provider::RemoteFile 17:51:54 action [:create] 17:51:54 default_guard_interpreter :default 17:51:54 use_etag true 17:51:54 use_last_modified true 17:51:54 cookbook_name "image-win-tableau-master" 17:51:54 checksum nil 17:51:54 backup 5 17:51:54 path "C:/InstallationMedia/TableauServer-64bit.exe" 17:51:54 verifications [] 17:51:54 rights nil 17:51:54 deny_rights nil 17:51:54 inherits true 17:51:54 declared_type :remote_file 17:51:54 atomic_update true 17:51:54 retries 0 17:51:54 retry_delay 2 17:51:54 not_if { #code block } 17:51:54 end 17:51:54 17:51:54 System Info: 17:51:54 ------------ 17:51:54 chef_version=13.0.118 17:51:54 platform=windows 17:51:54 platform_version=6.3.9600 17:51:54 ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32] 17:51:54 program_name=C:/opscode/chef/bin/chef-solo 17:51:54 executable=C:/opscode/chef/bin/chef-solo 17:51:54 17:51:54 17:51:54 ================================================================================ 17:51:54 Error executing action `create` on resource 'aws_s3_file[C:/InstallationMedia/TableauServer-64bit.exe]'
> 17:51:54 ================================================================================
> 17:51:54
> 17:51:54 Net::HTTPServerException
> 17:51:54 ------------------------
> 17:51:54 remote_file[C:/InstallationMedia/TableauServer-64bit.exe] (C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/aws/resources/s3_file.rb line 149) had an error: Net::HTTPServerException: 403 "Forbidden"
> 17:51:54
> 17:51:54 Resource Declaration:
> 17:51:54 ---------------------

I don't think this is the same issue please open a new one. But it looks like you either are not specifying credentials or are using credentials that do not have access to run the resource. See: https://github.com/chef-cookbooks/aws#credentials
