### ISSUE TITLE
Add source_url and issues_url, update CONTRIBUTING

### ISSUE THREAD

**Issue by iennae** [chef-cookbooks/aws#122]
Source URL Issues URL allow for supermarket to automatically show the "show issues and show source" when looking around at cookbooks. Without these in the metadata, these have to be handcrafted.

Expected format
source_url ""
issues_url ""

Contributing has some issues referring to retired wiki.

**Comment by ajohnstone** [comment]
This now causes a problem with amazon opsworks.

```
Fetching 'ark' from git@github.com:opscode-cookbooks/ark.git (at master)
Fetching 'aws' from git@github.com:opscode-cookbooks/aws.git (at master)
STDERR: Ridley::Errors::FromFileParserError Could not parse `/tmp/d20150408-4505-1uchrp6/metadata.rb': undefined method `source_url' for #<Ridley::Chef::Cookbook::Metadata:0x007f86d0728090>
---- End output of /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks ----
Ran /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks returned 47
```

**Comment by tas50** [comment]
This should be fixed by the responds_to use.

**Comment by jpooler** [comment]
I'm getting this error using Chef 11.10 and Berkshelf 3.2.0 in AWS Opsworks. 

I noticed ohai doesn't have the responds_to lines, which I assume means it's not backwards compatible. I tried removing it and got a compat_resource error, which indicated chef12 only.

Help?

**Comment by tas50** [comment]
The Ohai dependency is for the ohai cookbook not a new bit of metadata. If you're using Chef 11 though you will need to pin the version of the ohai cookbook elsewhere as that cookbook is Chef 12 only and will cause your runs to fail.  I'd highly recommend updating to the latest Opsworks with Chef 12. It resolves a lot of issues and provides loads of new functionality.

**Comment by jpooler** [comment]
Thanks for the fast reply @tas50 . I agree/it's on the docket to upgrade, just clearing out some other tech-debt first.
