### ISSUE TITLE
EBS volume creation is broken using AWS SDK v2 gem

### ISSUE THREAD

**Issue by drywheat** [chef-cookbooks/aws#127]
I believe this has been broken since https://github.com/opscode-cookbooks/aws/commit/2a183fd3e8fbfab09a8379192be4b0c4213e949a. 

The `aws-sdk` gem introduced response paging in v2 and this requires the user to extract the underlying collections (via method invocation) from the response pages. The current implementation does not account for that API shift.

[AWS response paging explained](http://ruby.awsblog.com/post/Tx2K7WCKKXEDCQT/Response-Paging)

I have tested this use `aws-sdk` **v2.0.22** (attribute version) and **v2.0.38** (latest at the time of this writing).

**Comment by drywheat** [comment]
See PR https://github.com/opscode-cookbooks/aws/pull/128 for fix.

**Comment by tas50** [comment]
The fix has been merged to master
