### ISSUE TITLE
Question about volume_id attribute

### ISSUE THREAD

**Issue by tonyjchong** [chef-cookbooks/aws#145]
Hi,

I have a recipe that uses the ebs_volume LWRP but on some of my nodes, the the volume_id attribute exists on some nodes, but on others it doesn't and I get the following error. All the machines in question have been provisioned the same way, using knife ec2 and are of the same role.

Please be advised that I have change the attribute name because of the way I'm loading the LWRP. Again, it works on some, but not on others. My question is, how do I get the attribute to populate on every node?

 ================================================================================
    Error executing action `update` on resource 'aws_resource_tag[my ebs volume]'
    ================================================================================

```
Chef::Exceptions::ValidationFailed
----------------------------------
Option resource_id's value my ebs volume does not match regular expression /(i|snap|vol)-[a-zA-Z0-9]+/

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/aws/providers/resource_tag.rb:83:in `load_current_resource'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/vungle/recipes/ebs_volume.rb

 62: aws_resource_tag 'my ebs volume' do
 63:   aws_access_key node[:vungle][:aws][:aws_access_key_id]
 64:   aws_secret_access_key node[:vungle][:aws][:aws_secret_access_key]
 65:   resource_id lazy { node[:aws][:ebs_volume][:data_volume][:volume_id] }
 66:   tags({"Name" => node[:machinename]})
 67: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/vungle/recipes/ebs_volume.rb:62:in `from_file'

aws_resource_tag("my ebs volume") do
  action :update
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name "vungle"
  recipe_name "ebs_volume"
  aws_access_key "fake_key"
  aws_secret_access_key "secret access"
  resource_id #<Chef::DelayedEvaluator:0x00000003f1be10@/var/chef/cache/cookbooks/vungle/recipes/ebs_volume.rb:65>
  tags {"Name"=>"machine01"}
end
```

**Comment by cheeseplus** [comment]
Is this still the case with the current client? It might be a limitation of lazy with validation but please let us know if it's present.

**Comment by iennae** [comment]
Please reopen if you still have a problem with the current client.
