### ISSUE TITLE
ebs_raid default 

### ISSUE THREAD

**Issue by iamzim** [chef-cookbooks/aws#148]
Error : aws_ebs_volume[sdi1](/var/chef/cache/cookbooks/aws/providers/ebs_raid.rb line 337) had an error: Aws::EC2::Errors::InvalidParameterValue: Value (/dev/sdi1) for parameter device is invalid. /dev/sdi1 is not a valid EBS device name.

Issue: /dev/sdi1 is invalid, /dev/sdi is not.

Details:
With mount_point set, ebs_raid takes the default from aws_ebs_volume: 
aws_ebs_volume disk_dev_path do
  device "/dev/#{disk_dev_path}"
  # set up our data bag info
  devices[disk_dev_path] = 'pending'
  Chef::Log.info("creating ebs volume for device #{disk_dev_path} with size #{disk_size}")

**Comment by guilhermef** [comment]
I'm having the same issue on Amazon AMI:

esb.rb:
```
  1: aws_ebs_raid 'es_disk1' do
  2:   mount_point '/es_data2'
  3:   disk_count 2
  4:   disk_size 200
  5:   level 0
  6:   disk_type "gp2"
  7: end
```

I get:
```
aws_ebs_volume("sdi1") do
  provider LWRP provider aws_ebs_volume from cookbook aws
  action [:create, :attach]
  updated true
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :aws_ebs_volume
  cookbook_name "es-cluster"
  size 200
  volume_type "gp2"
  piops 0
  device "/dev/sdi1"
end
```

And the error:
```
Aws::EC2::Errors::InvalidParameterValue
---------------------------------------
aws_ebs_volume[sdi1] (/var/chef/cache/cookbooks/aws/providers/ebs_raid.rb line 337) had an error: Aws::EC2::Errors::InvalidParameterValue: Value (/dev/sdi1) for parameter device is invalid. /dev/sdi1 is not a valid EBS device name.
```

**Comment by tas50** [comment]
We've removed the aws_raid provider so this bug is no longer valid for this cookbook. I encourage anyone that needs the functionality to take on the provider in its own codebase. As ebs_raid itself is not a core AWS service we don't see it as fitting here.
