### ISSUE TITLE
EBS Raid doesn't support Encryption (see #129)

### ISSUE THREAD

**Issue by DrMerlin** [chef-cookbooks/aws#164]
I wrote this up as part of #129.  The other part of #129 has been closed, so I'm opening a new issue just on this part.

PR #114 brought in the ability to create Encrypted EBS volumes, however it didn't provide a passthrough for volumes created as part of a raid to be created with encryption.  

I wrote PR #130 to fix this right after PR #114 was merged, but it included a general fix for EBS Raids that was sliced out into its own PR #156,  which was recently merged.  So I am submitting a new PR with just the remaining Encryption fix for volumes created in a Raid.

**Comment by tas50** [comment]
This has been merged in and will get released with our next cookbook release
