### ISSUE TITLE
ebs_volume Delete on Termination

### ISSUE THREAD

**Issue by jmassara** [chef-cookbooks/aws#167]
Would it be possible to add an attribute to `ebs_volume` that sets the `deleteOnTermination ` flag for volumes created/attached to an instance?  Currently we have to go in and manually clean up volumes after instances are pulled out of service.

**Comment by nineteen** [comment]
:+1:

**Comment by dtoubelis** [comment]
+1

**Comment by axs221** [comment]
+1

**Comment by JasonAtRook** [comment]
+2
