### ISSUE TITLE
Use of class variables causing resource issues

### ISSUE THREAD

**Issue by vancluever** [chef-cookbooks/aws#171]
Hello!

One thing that I noticed, in the updates that I'm making:

Use of class variables like this, say in `ec2.rb` line 45, is causing some variable data to be duplicated across interface instances across resources.

```
      def ec2
        @@ec2 ||= create_aws_interface(::Aws::EC2::Client)
      end
```

There are far-reaching implications for this, of course - basically if you want to have different resource attributes across the same service that have to do with connectivity data, you are by and large out of luck. It could also be leading to code where items are specified in one resource and were missed in another.

I stumbled upon this as I am working on a PR that, among other things, allows one to run the cookbook using local credentials and to specify region. This facilitates the cookbook to be run in local mode outside of an instance profile, working off your `~/.aws/credentials` file. Since there doesn't seem to be a way to get region out of API though (aside from environment), I have added a resource attribute for that (otherwise the cookbook falls back to instance profile, which doesn't work as I'm not running this within an EC2 instance). I noticed that I hadn't specified it within all resources, and when changed the IAM resources to use instanced-based variables, the resources that didn't have region specified predictably failed trying to grab instance data from `http://169.254.169.254/`.

What would the potential impact be to switch all of these items to instance varaibles? Switching the IAM resources to use an instance-based interface (by just altering it in my `libraries/iam.rb`) didn't really seem to cause issues, I was able to add the resources without issues.

Another part of my PR is the ability to assign resources to be deployed via assuming IAM roles thru STS (my company has multiple accounts and I want to manage resources centrally) so this I am predicting this being a bit more of an issue.

If some of this is not making sense, which I'm thinking it might not, feel free to look at the commits being made in the https://github.com/paybyphone/aws fork.

Thanks,

--Chris

**Comment by tas50** [comment]
Chris,

This was definitely an oversight and I've changed everything to instance variables now.
