### ISSUE TITLE
Disrespecting Travis

### ISSUE THREAD

**Issue by philoserf** [chef-cookbooks/aws#173]
From 1 failure 26 days ago to 16 today with commits directly against master I sense a degree of disrespect for Travis. 

If there is a desire to a) begin merging to branches and creating pull requests and b) caring about the travis build results, then lets do it.

**Comment by philoserf** [comment]
I had prepared two pull requests to begin addressing subject B. However project team commits directly to master without following a branch and pull request process has made contribution difficult.

**Comment by miketheman** [comment]
@philoserf I think you bring up an interesting topic, and @chef-cookbooks/aws-cookbook-collaborators should definitely get heads together and sort out how this should flow.
Thanks for bringing up the topic.

**Comment by miketheman** [comment]
@tas50 You're extremely active on committing to master directly, and there now also seems to be many PRs that were mergeable, that are no longer.

How do you want to proceed with maintaining this cookbook?

**Comment by tas50** [comment]
Sorry about breaking the world.  We worked pretty hard to get the cookbook project as a whole to a manageable state.  That required a lot of auto commits and a ton of boilerplate cleanup.  Some changes like adding the standardized rubocop file did break travis. The repos are now in a standardized state so the instability of this repo should be a thing of the past.
