### ISSUE TITLE
aws-sdk version 2.1 doesn't upgrade gems cleanly

### ISSUE THREAD

**Issue by huntertj** [chef-cookbooks/aws#176]
I have a need to use version 2.1.x in order to use AssumeRoleCredentials
so I've added in my calling recipe attributes
```
default['aws']['aws_sdk_version'] = '>= 2.1' 
```
This works fine on first install, however the problem comes up when a new version of the gem is released, such happened recently
```
Unable to activate aws-sdk-resources-2.1.24, because aws-sdk-core-2.1.23 conflicts with aws-sdk-core (= 2.1.24)
```

I can workaround this manually by doing a chef gem install on the three packages together, but I'm not sure how to work around this either in my wrapper or by editing the aws cookbook

**Comment by tas50** [comment]
We've updated the gem to the 2.2.X series now and I've yet to see this issue.  If you still see it with 2.2.X feel free to open this up again
