### ISSUE TITLE
depends 'ohai', '>=2.1.0' invalid

### ISSUE THREAD

**Issue by kpmueller** [chef-cookbooks/aws#206]
This line in metadata.rb is producing errors:

depends 'ohai', '>=2.1.0'

E, [2016-01-26T15:51:14.256721 #96714] ERROR -- : Ridley::Errors::HTTPBadRequest: {"error":["Invalid value '>=2.1.0' for metadata.dependencies"]}
E, [2016-01-26T15:51:14.256818 #96714] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.3.1/lib/ridley/middleware/chef_response.rb:24:in `on_complete'

**Comment by scalp42** [comment]
yeah seeing the same right now @tas50

**Comment by jslusher** [comment]
Here too. I worked around it by locking to version 2.9.0 in my Berksfile.

**Comment by tas50** [comment]
The space has been added in 2.9.2.  Sorry about that.
