### ISSUE TITLE
ohai[reload] executing during every converge

### ISSUE THREAD

**Issue by jsmickey** [chef-cookbooks/aws#211]
I have a wrapper cookbook with:
  include_recipe 'aws::ec2_hints'

The recipe runs and works as expected.  But the following is being run every time
```
ohai 'reload' do
  action :nothing
end.run_action(:reload)
```
Chef log shows this:
```
* ohai[reload] action reload/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.5.0/lib/ohai/plugins/solaris2/network.rb:57: warning: already initialized constant ETHERNET_ENCAPS
       /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.5.0/lib/ohai/plugins/solaris2/network.rb:57: warning: previous definition of ETHERNET_ENCAPS was here
       
           - re-run ohai and merge results into node attributes
```
I get the same output on every converge.  The OS is Ubuntu 14.04.  I'm not sure about the references to solaris2.  Is anybody else seeing this output?  Any ideas on how to fix this?

**Comment by tas50** [comment]
Closing this in favor of your other issue at https://github.com/chef-cookbooks/ohai/issues/31

We will be getting to that issue in the near future once we wrap up work on this cookbook.
