### ISSUE TITLE
EBS Volume from other volume does not obey most_recent_snapshot

### ISSUE THREAD

**Issue by viyh** [chef-cookbooks/aws#214]
I'm creating an EBS volume by using a volume ID as the initial snapshot_id in the resource. Even with most_recent_snapshot set to true, the oldest snapshot is always used.

aws_ebs_volume 'aem_ebs_volume' do
    size 1000
    device '/dev/sdi'
    volume_type 'gp2'
    most_recent_snapshot true
    action [:create, :attach]
    snapshot_id 'vol-a1b2c3d4'
end

Any ideas?

**Comment by darwin67** [comment]
encountered same issue here too.

**Comment by darwin67** [comment]
This issue should be fixed from my changes so i think it can be closed
