### ISSUE TITLE
3.3.0 breaks in our enviroment

### ISSUE THREAD

**Issue by corbesero** [chef-cookbooks/aws#233]
This latest version broke in an aws environment.  Specifically, using aws_s3_file failed with a 
"undefined method `compile_time' for Chef::Resource::ChefGem" error.
I have attached the relevant chef-client log section.

We are using chef-client 11.12.8 with a enterprise chef 11 server.

[aws-3.3.0-error-log.txt](https://github.com/chef-cookbooks/aws/files/189888/aws-3.3.0-error-log.txt)

**Comment by tas50** [comment]
@corbesero I just release 3.3.1 which should restore support for Chef 11.  Give it a try and open this back up if it's still happening.

**Comment by corbesero** [comment]
@tas50 looks good.  thank you
