### ISSUE TITLE
Consider dropping default EBS volume type

### ISSUE THREAD

**Issue by eherot** [chef-cookbooks/aws#248]
Right now if `volume_type` is not specified, this cookbook falls back to `standard` which is a bit misleading because the current Amazon API default is `gp2` (per [the docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html)). Since the API has its own concept of a default, I think it would make more sense to fall back to not sending a volume type when one is not specified, and letting the API fall back to whatever its current default is.

Alternatively, consider updating the default to be `gp2` to be consistent with the upstream API.

**Comment by tas50** [comment]
So I removed the default in https://github.com/chef-cookbooks/aws/pull/279, but it's actually still standard when you spin up a volume w/o specifying the type.
