### ISSUE TITLE
aws_ebs_raid  fails to mount new raid volume on ubuntu 16.04LTS

### ISSUE THREAD

**Issue by DoctorOgg** [chef-cookbooks/aws#251]
### Cookbook version

3.4.1
### Chef-client version

Chef: 12.12.15
### Platform Details

Ubuntu
us-east-1   xenial  16.04 LTS   amd64   ebs-ssd 20160721    ami-656be372    aki-919dcaf8

 knife ec2 server create \
    --run-list 'role[mongo]' \
    --image ami-656be372 \
    --flavor m3.large \
    --node-name mongo1.mongo.prod1 \
    --security-group-ids xxxx \
    --tags Name=mongo1,environment=prod1,role=mongo \
    --ssh-key ops \
    -i .ssh/oun-ops.pem \
    --ssh-user ubuntu \
    --environment prod1 \
    --subnet xxxx \
    --availability-zone us-east-1a \
    --ebs-size 30
### Scenario:

trying to build an raid 10 array and mount 
### Steps to Reproduce:

including the AWS cookbook in my own, 

aws_ebs_raid "Setup Mongo Raid" do
  mount_point_owner node["oun-mongo"]["user"]
  mount_point_group node["oun-mongo"]["group"]
  aws_access_key xxx
  aws_secret_access_key xxx
  mount_point node["oun-mongo"]["db_mount"]
  disk_count node["oun-mongo"]["ebs"]["number_of_disks"]
  disk_size node["oun-mongo"]["ebs"]["disk_size"]
  level node["oun-mongo"]["ebs"]["raid_level"]
  disk_type node["oun-mongo"]["ebs"]["disk_type"]
  mount_point_mode node["oun-mongo"]["ebs"]["mount_point_mode"]
  disk_piops node["oun-mongo"]["ebs"]["provisioned_iops"]
  disk_encrypted node["oun-mongo"]["ebs"]["encrypted"]
  disk_kms_key_id xxxx
end
### Expected Result:

i would like a raid 10 array mounted as request 
### Actual Result:

https://gist.github.com/neallawson/ad3af0d92224b5744b6480fc8fa0fb63

**Comment by neallawson** [comment]
Update: this issue seems to be specific to the newer ubuntu 16.04 LTS as it works on ami-3ddd502a , Ubuntu 14.04LTS

**Comment by pg1671** [comment]
+1 .. as above .. works fine on 14.04

**Comment by tas50** [comment]
The ebs_raid provider needs a complete rework and I'm hesitant to make the time commitment since it's not actually a core AWS feature, but a bolt on that really should have ended up in its cookbook. It makes a lot of assumptions about volume layout that just don't pan out across instance types and distro releases.  If someone wants to take on a refactor that works on PV/HVM and multiple distro releases I'd gladly merge it, but in the current state I'm more inclined to just remove the provider altogether.

**Comment by neallawson** [comment]
Please leave it, i have found it very essential to many of my cookbooks, i would love to also see an LVM build in as well

**Comment by michaeldauria** [comment]
Perhaps there is a way to string a RAID array together using the `ebs_volume` provider along with the `mdadm` cookbook and replace the `ebs_raid` provider with a nice example of this instead?

**Comment by tas50** [comment]
We've removed the aws_raid provider so this bug is no longer valid for this cookbook. I encourage anyone that needs the functionality to take on the provider in its own codebase. As ebs_raid itself is not a core AWS service we don't see it as fitting here.

**Comment by DoctorOgg** [comment]
thank you for letting us know, however i must say im disappointed, and found the functionality useful.

**Comment by tas50** [comment]
I highly recommend provisioned IOPS on an EBS volume where you can

**Comment by DoctorOgg** [comment]
yup, however when the business have a requirement, you code to the requirement....  and that was my use case for this feature...

**Comment by tas50** [comment]
If you run the existing PV instances where this functionality worked you can just copy the resource/provider into a local cookbook.
