### ISSUE TITLE
uninitialized constant Aws on Opsworks

### ISSUE THREAD

**Issue by odg0318** [chef-cookbooks/aws#253]
Cookbook version: 3.4.1
Chef-client version: 11.10.4

Hello,
(Sorry for my poor English in advance.)

I tried to tag my instance using `aws_resource_tag` on Opsworks.
My custom cookbook works fine with aws cookbook 2.5.0 which uses `right_aws` gem to connect to the AWS API.
I cannot use `right_aws` anymore because an endpoint of `northeast` region is invalid in `right_aws`.
`right_aws` generates an endpoint `ap-{region}.ec2.amazonaws.com` not `ec2.ap-{region}.amazonaws.com` referred in http://docs.aws.amazon.com/ko_kr/general/latest/gr/rande.html#ec2_region

So I want to upgrade to the latest aws cookbook, which uses `aws-sdk` gem instead of `right_aws`.
I guess that two versions of `aws-sdk` gem conflict each other: 1.65.0 and 2.2.0.
Chef for Opsworks cannot find the module named `Aws` (2.2.0), but instead finds the module `AWS` (1.65.0) (in all capitals) on runtime.

How can I use the latest version in Chef 11.10.4 of Opsworks?

```
================================================================================
Error executing action `update` on resource 'aws_resource_tag[i-431a284d]'
================================================================================
 
 
NameError
---------
uninitialized constant Aws
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/aws/libraries/ec2.rb:30:in `ec2'
/var/lib/aws/opsworks/cache.stage2/cookbooks/aws/providers/resource_tag.rb:90:in `load_current_resource'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/resource-tagging/recipes/v2.rb
 
14: aws_resource_tag node[:opsworks][:instance][:aws_instance_id] do
15:   tags tags
16:   action :update
17: end
18: 
 
 
 
Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/resource-tagging/recipes/v2.rb:14:in `from_file'
 
aws_resource_tag("i-431a284d") do
action [:update]
retries 0
retry_delay 2
cookbook_name "resource-tagging"
recipe_name "v2"
tags {"cTags"=>"o=guri;t=kr-devops;m=personaldev;p=enswers;e=dev;r=ac02", "Purpose"=>"personaldev", "Name"=>"ens-personalde-a040-431a284d-AC02"}
end
```

**Comment by tas50** [comment]
This cookbook requires Chef 12 and the more modern Opsworks. It simply isn't going to work on Chef 11 and the legacy Opsworks. You'll need to upgrade your Opsworks to utilize this cookbook.

**Comment by odg0318** [comment]
I found the solution that is a kind of monkey patch.

I will write my solution shortly for users of Opsworks with Chef 11.
Opsworks with Chef 11 basically uses `aws-sdk-v1`, which conflicts with `aws-sdk-v2` in `aws` cookbook.
As a result, `aws-sdk` gem to be installed in compile time is useless.

1) Make a tar file including gem files that `aws-sdk-v2` needs.
2) Monkey-patch `Opscode::aws::require_aws_sdk` that is called at the run-time.
```ruby
module Opscode
  module Aws
    def require_aws_sdk
      $:.unshift *Dir[File.expand_path("#{Chef::Config[:file_cache_path]}/gems/**/lib", __FILE__)]
      require 'aws-sdk-v2'
    end
  end
end
```
3) Create new recipe to install a tar file that is made at first step.
```ruby
aws_lib_name = 'aws-libs.tar.gz'

cookbook_file "#{Chef::Config[:file_cache_path]}/#{aws_lib_name}" do
  source aws_lib_name
  action :nothing
end.run_action(:create)

execute 'extract aws libraries' do
  command "tar xvfz #{Chef::Config[:file_cache_path]}/#{aws_lib_name} -C #{Chef::Config[:file_cache_path]}"
end
```
4) Include the `install` recipe before `aws cookbook` is used.

You can see my solution below link.
https://github.com/odg0318/chef-aws-cookbook-with-chef11

I hope this solution helps someone.
