### ISSUE TITLE
Fails to find EBS volume when creating volume. 

### ISSUE THREAD

**Issue by bitwes** [chef-cookbooks/aws#259]
### Cookbook version
3.4.1

### Chef-client version
12.4.1

### Platform Details
CentOS 6.6

### Scenario:
When creating a volume the cookbook routinely hits the `raise "Volume #{nv[:volume_id]} no longer exists"`.  I'm suspect that this is an AWS issue that the provider does not take into account.  We started seeing it sometime after 8/18 (that was the last time we had a box spin up that worked that we know of).  For some reason we do not see this issue when using kitchen to spin up a box.  We only see it when the box is spun up using a cft.

### Steps to Reproduce:
Below is a simple script that replicates the logic in the ebs_volume provider.  When run on an AWS instance we are seeing 4 "not there yet" messages (replaces the `raise` in the provider) before it finds the volume.  In all cases the volume is indeed created, but it is not found initially.  On occasion the script will print the volume state as "creating" and there are not any "not there yet" messages.  This is what makes me think that AWS isn't reporting things back correctly and the provider thinks the volume is gone.

Maybe some tolerance for an empty results set can be added to the loop, or a minimum timeout could be implemented and then remove the `raise`.  In my experimenting, a sleep of 3 seconds after the creation of the volume resulted in it finding the volume every time.

I've run this about 50 times, creating 8 and 1 GiB volumes and got pretty consistent results.

### Expected Result:
It should find the volume that it created.

### Actual Result:
It does not.

### Test Script
```
require 'aws-sdk'
require 'aws-sdk-core'

def main(timeout=0)
  creds = Aws::SharedCredentials.new()
  ec2 = Aws::EC2::Client.new(credentials: creds)

  params = { availability_zone: 'us-east-1b', volume_type: 'gp2', encrypted: false}
  params[:size] = 1
  nv = ec2.create_volume(params)

   begin
    Timeout.timeout(timeout) do
      loop do
        vol = ec2.describe_volumes[:volumes].find { |v| v[:volume_id] == nv[:volume_id] }
        if vol && vol[:state] != 'deleting'
          if ['in-use', 'available'].include?(vol[:state])
            puts("Volume #{nv[:volume_id]} is available")
            break
          else
            puts("Volume is #{vol[:state]}")
          end
          sleep 3
        else
          #fail "Volume #{nv[:volume_id]} no longer exists"
          puts "not there yet"
        end
      end
    end
  rescue Timeout::Error
    raise "Timed out waiting for volume creation after #{timeout} seconds"
  end
end

time = ARGV.size() == 1 ? ARGV[0].to_i : 0
main(time)
```

**Comment by tas50** [comment]
This will be fixed in the 4.1.1 release, which I'll be doing in just a few minutes
