### ISSUE TITLE
 NameError: undefined local variable or method `node'

### ISSUE THREAD

**Issue by marcomancuso** [chef-cookbooks/aws#260]
### Cookbook version

4.0.0
### Chef-client version

12.13.37
### Platform Details

Centos 7.2
### Scenario:

Trying to install the aws-sdk and use the api
### Steps to Reproduce:

I am writing a library to create s3 buckets

```
class Chef
  module BucketCreator
    class << self
      include Chef::Mixin::ShellOut
      include Opscode::Aws

      def create_bucket(bucket_name)
          require_aws_sdk
          s3 = Aws::S3::Client.new()
          begin
            s3.create_bucket(bucket: bucket_name)
          rescue Aws::S3::Errors::BucketAlreadyExists
               puts 'Max number retry reached'
          end
        end
      end
    end
  end
end
```

But when including it in a recipe and running it, I get the error:

```
[2016-09-19T13:02:52+00:00] ERROR: ruby_block[start-instance] (commons::start-instance line 3) had an error: NameError: undefined local variable or method `node' for Chef::BucketCreator:Module
```

The reason is that the library has not access to the Chef `node` object
### Expected Result:

I should be able to run the `require_aws_sdk` method with no exception
### Actual Result:

Error shown above.

Is there another way to do what I'm trying to achieve?
Thanks

**Comment by maakn786** [comment]
I'm not getting the same results with centOS. Were you able to use other AWS services ?

**Comment by tas50** [comment]
While technically the libraries here can be used as true libraries and consumes elsewhere that's not something we're supporting going forward. I'd highly suggest just using the AWS SDK directly. It'll probably take less effort.
