### ISSUE TITLE
ebs_volume failed to find just created volume in wait loop

### ISSUE THREAD

**Issue by coltzhao** [chef-cookbooks/aws#261]
### Cookbook version
2.7.2

### Chef-client version
11.8.2

### Platform Details
ubuntu 12.04

### Scenario:
On AWS, setup mongodb cluster and in the process of creating an ebs raid with 2 ebs volumes

I know my version are old, but from my debugging, it is nothing to do with the old version.
details below:

### Steps to Reproduce:
I do not think it is easy to reproduce with bare minimum test, and it is in fact a timing issue.

Here is what happened:
when I try to set up an ebs raid with 2 volumes, after create volume with an old snapshot (that has a bunch of data).
I running into error as:

```
================================================================================
Error executing action `create` on resource 'aws_ebs_volume[sdi1]'
================================================================================


RuntimeError
------------
Volume vol-xxxxxxx no longer exists


Cookbook Trace:
---------------
/var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:198:in `block (2 levels) in create_volume'
/var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:187:in `loop'
/var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:187:in `block in create_volume'
/var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:186:in `create_volume'
/var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:38:in `block (2 levels) in class_from_file'
/var/chef/cache/cookbooks/aws/providers/ebs_volume.rb:37:in `block in class_from_file'


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/aws/providers/ebs_raid.rb

338:     aws_ebs_volume disk_dev_path do
339:       aws_access_key creds['aws_access_key_id']
340:       aws_secret_access_key creds['aws_secret_access_key']
341:       aws_session_token creds['aws_session_token']
342:       size disk_size
343:       volume_type disk_type
344:       piops disk_piops
345:       device "/dev/#{disk_dev_path}"
346:       name disk_dev_path
347:       action [:create, :attach]
348:       snapshot_id creating_from_snapshot ? snapshots[i - 1] : nil
349:       provider 'aws_ebs_volume'
350: 
351:       # set up our data bag info
352:       devices[disk_dev_path] = 'pending'
353: 
354:       Chef::Log.info("creating ebs volume for device #{disk_dev_path} with size #{disk_size}")
355:     end
356: 



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/aws/providers/ebs_raid.rb:338:in `block in create_raid_disks'

aws_ebs_volume("sdi1") do
  provider Chef::Provider::AwsEbsVolume
  action [:create, :attach]
  retries 0
  retry_delay 2
  cookbook_name "mongodb-ebs"
  size 10
  volume_type "standard"
  piops 0
  device "/dev/sdi1"
  snapshot_id "snap-xxxxxxxx"
  timeout 180
end
```

Now when I debug, I found that the [line](https://github.com/chef-cookbooks/aws/blob/v2.7.2/providers/ebs_volume.rb#L188) does ___not___ return volume data.

And further check [line](https://github.com/chef-cookbooks/aws/blob/v2.7.2/providers/ebs_volume.rb#L136), seems it will only not get the newly created volume, and old volumes are there, just not the new one.

I added `sleep 30` after [line](https://github.com/chef-cookbooks/aws/blob/v2.7.2/providers/ebs_volume.rb#L182), and it fixed the problem.

This ___only___ happen recently, not sure because of the snapshot contains more data? or AWS changed something.
I believe this can occur even in newest version of this cookbook.

**Comment by brucelee123** [comment]
Same thing is happening to me. The new volume gets the error during the "create" action. Digging deeper, it actually gets that error when running cookbooks/aws/libraries/ec2.rb .. ec2.create_volume( ... ). I haven't drilled deeper than that though. This only started happening recently, and what's weird is it only happens on US-West 1 for me. Other regions work fine. We're also using a forked version of this cookbook, with no changes recently, so I doubt it's anything to do with the code in this cookbook, but rather something changing on AWS's end. @coltzhao

**Comment by blakeh** [comment]
I'm experiencing the exact same issue in us-east. I haven't tried other regions yet. This has worked flawlessly for me for months. And I've had no reason to change the script so something has happened internally to AWS I'm pretty sure. I'll try a longer timeout as well and see what happens.

**Comment by dphe** [comment]
I had the same issue too.  I updated the cookbook to the latest 4.1.1 version and everything works fine.  Just download and install the latest aws cookbook with related dependencies and it should work fine.

**Comment by tas50** [comment]
This has been fixed in the current version. The AWS API behavior changed and caused the cookbook to start failing.

**Comment by analogrithems** [comment]
having the same issue
