### ISSUE TITLE
Cloudwatch Argument Error, wrong number of arguments (3 for 1...2)

### ISSUE THREAD

**Issue by wesleywh** [chef-cookbooks/aws#269]
### Cookbook version
4.2.0

### Chef-client version
12.2.1

### Platform Details
AWS Windows Server 2012 Base running Opsworks

### Scenario:
I simply want to run a recipe successfully that uses the aws cookbook. I have a local copy of the aws cookbook and a custom recipe that I use:

  `depends 'aws', '~> 4.2.0`' 

in the metadata.rb file. 

### Steps to Reproduce:
I ran the following command:

   `chef-client --local-mode --override-runlist "recipe[mycookbook::default]"`

locally on the aws windows server 2012 base instance that was part of an opsworks layer. 

### Expected Result:
Successful execution of my recipe without compile errors.

### Actual Result:
It returned the following:
`
     ===================================================================
     Recipe Compile Error in C:/Users/.../.chef/local-mode-cache/cache/cookbooks/aws/resources/cloudwatch.rb
     ===================================================================

    ArgumentError
    --------------------
    wrong number of arguments (3 for 1..2)
`

Currently I am **not** using the cloudwatch support provided here so I tried commenting out everything in the "aws/resources/cloudwatch.rb" file. When I did that everything compiled and ran perfectly.

**Comment by ubirajaramneto** [comment]
+1 for that, I am also running into this issue, going to comment out the file to see if it works.

**Comment by pcseh** [comment]
Same issue here.

**Comment by ubirajaramneto** [comment]
pcseh, just comment out the file "aws/resources/cloudwatch.rb" and it should work, at least for me it worked.

**Comment by pcseh** [comment]
@ubirajaramneto : Thanks, I will try it. :)

**Comment by hiteshmahajan** [comment]
Facing same issue need a quick fix on this .

**Comment by wesleywh** [comment]
If you're not using cloudwatch then try commenting out aws/resources/cloudwatch.rb until a fix is presented. If that doesn't work, not sure what else to do right now.

**Comment by tas50** [comment]
@pcseh @ubiquitousthey @hiteshmahajan What versions of chef are you running?

**Comment by pcseh** [comment]
@tas50 : chef-server v11.1.7

**Comment by pcseh** [comment]
@tas50 : Do you have any idea? Chef-server v11.1.7 and chef-client v12.4.3

**Comment by dbrownxc** [comment]
Ran into same issue testing in kitchen.  I went back to 4.2.2 to support Chef 12.2 to match OpsWorks and encountered this.
I resolved my issue by going back to 4.1.3.  Here is the error with a line number.

I think this line is missing "kind of:".  This is my first Chef\Ruby project so I'm not sure.

wrong number of arguments (3 for 1..2)
C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cookbooks\aws\resources\cloudwatch.rb:14:in class_from_file

13:  attribute :extended_statistic, kind_of: String
14>> attribute :dimensions, Array, default: []
15:  attribute :period, kind_of: Integer

**Comment by tas50** [comment]
Any chance people could give me their complete run list. It would be helpful for debugging this one

**Comment by tas50** [comment]
Also if everyone could try out the 6.1 release I converted this over to a custom resource which *may* clear up some of the odd mismatching we're seeing here

**Comment by tas50** [comment]
I'm going to close this out at this point. If someone can reproduce this on the latest cookbook with a later version of Chef 12 I'll gladly dig in.
