### ISSUE TITLE
Unable to tag ec2 instance

### ISSUE THREAD

**Issue by wesleywh** [chef-cookbooks/aws#272]
### Cookbook version
4.2.0

### Chef-client version
12.1

### Platform Details
Amazon Linux 
amzn-ami-hvm-2016.09.1.20161221-x86_64-gp2 (ami-1e299d7e)

### Scenario:
I want to have the instance tag itself with a series of tags.

### Steps to Reproduce:
Using a recipe call "aws::tag_instance". With the following:

```
include_recipe "aws"

aws_resource_tag node['ec2']['instance_id'] do
    tags(node['tag-list'])
    action :update
end
```
and supply the following json to it
```
{
  "tag-list":{
    "tag1":"true",
    "tag2":"true"
  }
}
```
### Expected Result:
Have my tags appear after successful completion of the chef setup.

### Actual Result:
I get the following error:
```
Aws::EC2::Errors::UnauthorizedOperation
---------------------------------------
You are not authorized to perform this operation.

Resource Declaration:
---------------------
3: aws_resource_tag node['ec2']['instance_id'] do
4:     tags(node['tag-list'])
5:     action :update
6: end

Compiled Resource:
------------------
aws_resource_tag("<instance_id_was_here>") do
action [:update]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :aws_resource_tag
cookbook_name "aws"
recipe_name "tag_instance"
tags {"tag1"=>"true", "tag2"=>"true"}
end

Platform:
---------
x86_64-linux
```

I was thinking it was an IAM role issue since the documentation states that I can use IAM roles for this:
`aws_secret_access_key, aws_access_key and optionally aws_session_token - required, unless using IAM roles for authentication.`

IAM Role Permission:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DeleteTags"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Am I just doing something wrong here or is this a bug?**

**Comment by wesleywh** [comment]
I got tired of waiting so I just made a recipe that just works with IAM roles. 

```
execute "Tag Instance" do
  node.default[:compiled_array]=""
  node[:tags].each_with_index do |key_value, index|
    if "#{index}" != "0"
      node.default[:compiled_array]+="  "
    end
    node.default[:compiled_array]+="Key=#{key_value[0]},Value=#{key_value[1]}"
  end
  command "aws ec2 create-tags --tags #{node[:compiled_array]} --region #{node[:region]} --resources #{node[:ec2][:instance_id]}"
  action :run
end
```

Supply the json like the following:
```
{
	"region":"us-west-2",
	"tags":{
			"mykeyname1":"true",
			"mykeyname2":"true"
		}
}
```

Hopefully this will help someone that is having the same problem as me. You will have to make something to check to make sure the tag doesn't already exist or something if you care about that sort of thing. For me this will only ever be executed once.

**Comment by cheeseplus** [comment]
Pretty sure this needed `"ec2:DescribeTags"` tags set as well.

**Comment by cheeseplus** [comment]
As it seems you've found a workaround and our documentation states DescribeTags is need in the readme I'm closing this one. Please do open a new issue if trying with the documented permissions and we're happy to take a look.
