### ISSUE TITLE
Timeout on large file downloads from S3 with s3_file

### ISSUE THREAD

**Issue by markunsworth** [chef-cookbooks/aws#273]
### Cookbook version
4.2

### Chef-client version
12.13.37

### Platform Details
Ubuntu 14.04 on AWS

We're trying to download a relatively large, text file (3GB) but it results in a 403 forbidden exception. Looking ath the logs it takes almost 3mins just to decide that the local and remote files do not match, this is presumably down to the loading of the existing file line by line to calculate an MD5 hash.

    [2017-02-10T12:20:45+00:00] INFO: Processing aws_s3_file[/home/my_user/very_large_file.txt] action create (mycookbooks::corenlp line 43)
    [2017-02-10T12:23:20+00:00] INFO: Remote and local files do not match, running create operation.
    [2017-02-10T12:23:20+00:00] INFO: Processing remote_file[/home/myuser/very_large_file.txt] action create (/var/chef/runs/1/local-mode-cache/cache/cookbooks/aws/providers/s3_file.rb line 40)
    [2017-02-10T12:25:55+00:00] INFO: HTTP Request Returned 403 Forbidden

By the time the file actually starts to download it seems like the url has expired as it's only created with a 5 min expiration.

Options to fix this, not limited to:

1. Calulate the [presigned url](https://github.com/chef-cookbooks/aws/blob/master/providers/s3_file.rb#L28) just before attempting the download (it seems it's not used in calculating the hash, but I may be wrong)
2. Allow overriding of the link expiry (currently it's set to [300 seconds](https://github.com/chef-cookbooks/aws/blob/master/providers/s3_file.rb#L28))
3. Provide an option for skipping of md5 comparison step when using `:create` action

I think the first option makes the most sense.

**Comment by markunsworth** [comment]
I've gone ahead and created a pull request for the first option which does fix this particular issue for me, however it could still cause issues.

In the event that the first attempt to download takes > 5 mins, then fails and the resource specifies a number of retries then the second retry would still result in a 403 forbidden error.

This issue also raises the question on the suitability of how the MD5 hash is being calculated as I know the file on S3 hasn't changed and we have to wait for the file to be redownloaded on every deployment. We can work around this but I wonder if it could still be worth having an option skipping the MD5 hash check.

**Comment by smurawski** [comment]
Closed by #274 - thanks for reporting and the PR to fix it!


![](https://m.popkey.co/25ab56/jw1rj.gif)
