### ISSUE TITLE
aws cloudformation resource create does not wait till the stack is successfully executed

### ISSUE THREAD

**Issue by kamalika-majumder** [chef-cookbooks/aws#277]
### Cookbook version
cookbook 'aws', '~> 4.2.0'

### Chef-client version
latest
### Platform Details
centos 7

### Scenario:
I am using the aws_cloudformation_stack resource and it returns successful by just creating rhe stack. It does not wait till the stack is created successfull and does not fail if it rollbacks.

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by cheeseplus** [comment]
The AWS SDK doesn't have any facility for this - this is just how CloudFormation works. I think it's a bit out of scope for the cookbook to behave counter to the CLI and API tooling in this regard and would be a bit of a bear to support.

**Comment by tas50** [comment]
Closing this out since there's not really a way for us to handle this
