### ISSUE TITLE
Forbidden url error on aws_s3_file

### ISSUE THREAD

**Issue by jeusdi** [chef-cookbooks/aws#280]
### Cookbook version
4.2

### Chef-client version
12.19.36

### Platform Details
Centos/7

### Scenario:
Download a file from a s3 bucket

### Steps to Reproduce:
According to [documentation][2], I've set this content in my recipe:

    aws = data_bag_item('aws', 'dev')
    
    aws_s3_file '/tmp/authz.war' do
      bucket 'living-artifacts-dev'
      remote_path 'authz/authz.war'
      aws_access_key aws['aws_access_key_id']
      aws_secret_access_key aws['aws_secret_access_key']
      region 'eu-central-1'
    end

All values are populated correctly and I've also tried to test them using aws-cli.

How could I debug this?

### Expected Result:
Download a file.

### Actual Result:
chef client is getting this message:

More detailed error message:

    * aws_s3_file[/tmp/authz.war] action create
    
    * chef_gem[aws-sdk] action install
    [2017-03-03T11:25:16+00:00] INFO: chef_gem[aws-sdk] installed aws-sdk at ~> 2.2
    
    - install version ~> 2.2 of package aws-sdk
    [2017-03-03T11:25:16+00:00] INFO: Remote and local files do not match, running create operation.
    * chef_gem[aws-sdk] action install (up to date)
    * remote_file[/tmp/authz.war] action create
    [2017-03-03T11:25:16+00:00] INFO: HTTP Request Returned 403 Forbidden:
    [2017-03-03T11:25:16+00:00] WARN: remote_file[/tmp/authz.war] cannot be downloaded from https://living-artifacts-dev.s3.e
    u-central-1.amazonaws.com/authz/authz.war?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=sFo6JjohgYi%2BYi4Ut7pTy9EGVDCG89IROX%2Bw7E
    RR%2F20170303%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20170303T112516Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signatur
    e=f3c2b371ad4e1fe24745459adf0463c708e0363a139b598b04e40789c43ded7d: 403 "Forbidden"
    =========================================================================
    Error executing action `create` on resource 'aws_s3_file[/tmp/authz.war]'
    =========================================================================
    
    Net::HTTPServerException
    ------------------------
    remote_file[/tmp/authz.war] (/var/chef/cache/cookbooks/aws/providers/s3_file.rb line 40) had an error: Net::HTTPServerException: 403 "Forbidden"

I've tested it using aws command client. I've firstly set credentials using `aws configure` and I've provided requested values. So, this command:

    aws s3 cp s3://living-artifacts-dev/authz/authz.war authz.war

is correctly performed and file is downloaded.

  [1]: https://supermarket.chef.io/cookbooks/aws
  [2]: https://github.com/chef-cookbooks/aws#aws_s3_file

**Comment by cheeseplus** [comment]
This is likely an issue of the keys being incorrect, aws configure can source credentials resources from several different places but there ins't a way for us to verify the correct credentials are being used on your behalf.

**Comment by srinivas-anant** [comment]
Hi @jeusdi - Were you able to resolve the issue? I am also facing this right now, though rather than using IAM User Creds, I am using the IAM role attached to the instance. Manually on the instance when I run aws s3 cp command it downloads the files but when using the cookbook the file is not downloaded. 
@cheeseplus - Any reason this might be happening?

**Comment by wesleywh** [comment]
Since this is the first result when I google I figure I will post something people can follow to help them debug.
```
aws_s3_file "/my/local/path/item.war" do
    bucket "my-bucket"
    remote_path "my-folder/item.war"
    region "us-west-2"
    action :create
end
```
The biggest thing is that can give you a forbidden code is an incorrect path. Like a none existence folder or item name (wrong named).

Next you have to have this in your iam policy for your iam role/user:
```
{
       "Action": [
            "s3:GetObject"
        ],
        "Resource": [
            "arn:aws:s3:::my-bucket/my-folder/*"
        ],
        "Effect": "Allow"
}
```
