### ISSUE TITLE
uninitialized constant Opscode::Aws::Ec2

### ISSUE THREAD

**Issue by dillongilmore** [chef-cookbooks/aws#305]
### Cookbook version
Upgrade path from 6.1.1 to 7.1.1

### Chef-client version
Chef: 12.19.36

### Platform Details
Vagrant: vmware, virtualbox (seems arbitrary)
Host: Mac, Linux
Guest: CentOS 6

### Scenario:
Upgrading from 6.1.1 to 7.1.1

### Steps to Reproduce:
Provision a machine using the aws cookbook at version 6.1.1. We specifically are using the s3 file resource, but this seems arbitrary as the provision fails at the compile step (so no code is actually ran)

### Expected Result:
Machine to successfully/gracefully upgrade to the newest version of the cookbook and provision as normal.

### Actual Result:
Failed on the compile step.

**Comment by josephptata** [comment]
I experienced the same issue, it appears to be caused by some library files which were removed in this latest release.  If you using Berkshelf to package this as a dependency make sure to use the --delete option with your berks vendor command. 

That fixed the issue for me.

**Comment by tas50** [comment]
That library was part of the 6.X release and not the 7.X release so if you're hitting this error either some bits of the old cookbook are still leftover like @josephptata mentioned or you have a cookbook that was consuming these libraries directly.

**Comment by jkburges** [comment]
For anyone using the `vagrant-berkshelf` plugin, I have to blow away the associated berkshelf at `~/.berkshelf/vagrant-berkshelf/shelves/berkshelf-<some id>`.
