### ISSUE TITLE
method address rename in elastic_ip resource causing failures

### ISSUE THREAD

**Issue by shayangz** [chef-cookbooks/aws#306]
Commit b801533228a9341633236fb2ca5933ac6d534d6f renamed method `address` to `eip_info` without updating where it is used. This is picked up in `7.1.1` causing failures in the wild.

### Cookbook version
7.1.1

### Chef-client version
13.0.118

### Platform Details
ubuntu 16.04 on aws

### Scenario:
associate an EIP

### Steps to Reproduce:
using `aws_elastic_ip` resource

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
```
* aws_elastic_ip[attaching EIP (xxx.xxx.xxx.xxx) for 'foo.com'] action associate

    ================================================================================
    Error executing action `associate` on resource 'aws_elastic_ip[attaching EIP (xxx.xxx.xxx.xxx) for 'foo.com']'
    ================================================================================

    NoMethodError
    -------------
    undefined method `address' for Custom resource aws_elastic_ip from cookbook aws

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/aws/resources/elastic_ip.rb:15:in `block in class_from_file'

```

**Comment by tas50** [comment]
Fixed in https://github.com/chef-cookbooks/aws/commit/59d7596c35cb31fd9e1aab38ba5444bbd9775858

Looks like disassociate had been broken for a long time. That's been fixed as well. I'll cut a release for this

**Comment by shayangz** [comment]
Awesome! Thanks for the quick turnaround.
