### ISSUE TITLE
No resource or method named `do_s3_file' for `LWRP resource aws_s3_file from cookbook aws action provider

### ISSUE THREAD

**Issue by onetwopunch** [chef-cookbooks/aws#312]
### Cookbook version
7.1.2
### Chef-client version

```
$ chef-solo --version
Chef: 12.5.1
```
### Platform Details
Ubuntu 16.04

### Scenario:
I'm trying to download a file from S3 from within Vagrant. The credentials are passed into the s3 resource. I recently upgraded to aws cookbook 7.1.2 from 4.0.0 because I was getting a permission denied error even though I could use the aws cli with the same credentials to pull down the file. Now that I've upgraded to the newest version, I get the error:

```
No resource or method named `do_s3_file' for `LWRP resource aws_s3_file from cookbook aws action provider
```

### Steps to Reproduce:
You need a private bucket, we'll call it `private-bucket` and credentials stored as node attributes.

```
aws_s3_file "/opt/package.deb" do
  bucket 'private-bucket'
  remote_path "some/remote/package.deb"
  aws_access_key node['aws']['access_key_id']
  aws_secret_access_key node['aws']['secret_access_key']
  region 'us-west-2'
end
```

### Expected Result:
I'm expecting to have the remote file `s3://private-bucket/some/remote/package.deb` be downloaded to `/opt/package.deb` (obviously these are fake names to prevent information disclosure)

### Actual Result:
I get the error:

```
==> default: NoMethodError
==> default:     -------------
==> default:     No resource or method named `do_s3_file' for `LWRP resource aws_s3_file from cookbook aws action provider "/opt/package.deb"'
==> default:
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /opt/kitchen/librarian-cookbooks/aws/resources/s3_file.rb:34:in `block in class_from_file'
==> default:     /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:
==> default:     /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:     /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:     /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:     /opt/kitchen/librarian-cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
```

**Comment by tas50** [comment]
This cookbook requires Chef 12.9 or later. Chef 12.5 came out back in 2015. Try upgrading and it should work fine.
