### ISSUE TITLE
aws cookbook cloudformation resource does not support capability named IAM

### ISSUE THREAD

**Issue by LenOtuye** [chef-cookbooks/aws#315]
### Cookbook version
Latest

### Scenario:
Trying to deploy a cloudformation stack that creates named IAM policies: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html

### Expected Result:
Cookbook needs to add named_iam_capability property. This needs to be added to aws/resources/cloudformation_stack.rb, line 6 will need

property :named_iam_capability, [true, false], default: false

Line 81 will need to be updated to create an array that can include "CAPABILITY_NAMED_IAM" if the property above is true.

I'd make the changes, but my ruby knowledge is pretty limited.

**Comment by iennae** [comment]
Thanks for reporting this. I'm working on a PR for this change.

**Comment by tas50** [comment]
I'm closing this one out since we've released a fix. Thanks for the report
