### ISSUE TITLE
missing chefspec matchers

### ISSUE THREAD

**Issue by y0y0z** [chef-cookbooks/aws#318]
### Cookbook version
7.2.0

### Chef-client version
12.21.4

### Platform Details
ubuntu 16.04

### Scenario:
chefspec matcher is missing a matcher for `aws_instance_term_protection` lwrp.

### Steps to Reproduce:
add the following chefspec example:
```ruby
expect(chef_run).to enable_aws_instance_term_protection('enable termination protection')
```

### Expected Result:
chefspec will pass

### Actual Result:
there is no matcher so chefspec fails

**Comment by iennae** [comment]
Thanks for reporting. With the next release of this cookbook this will be fixed.
