### ISSUE TITLE
Cannot use after requiring aws-sdk-ssm

### ISSUE THREAD

**Issue by adecarolis** [chef-cookbooks/aws#323]
### Cookbook version
7.2.0

### Chef-client version
12.19.36

### Platform Details
Centos 6.6

### Scenario:
I'm trying to use aws_route53_record while aws-sdk-ssm is required

### Steps to Reproduce:
```
chef_gem 'aws-sdk-ssm'
require 'aws-sdk-ssm'
```
then try to use aws_route53_record()

### Expected Result:
I expected aws_route53_record() to work normally

### Actual Result:
aws_route53_record() fails with the following error:
`Gem::ConflictError: Unable to activate aws-sdk-resources-2.10.65, because aws-sdk-core-3.6.0 conflicts with aws-sdk-core (= 2.10.65)
`

**Comment by iennae** [comment]
Currently this cookbook uses aws-sdk version 2. It looks like you need to pin the version of the gem you are pulling in so that it doesn't try to pull in version 3 of the api.

**Comment by adecarolis** [comment]
I already came to the same conclusion you provided however this is a new gem/service and since the very first release (1.0.0rc1) the requirement has always been aws-sdk 3 or newer.

**Comment by iennae** [comment]
@adecarolis This cookbook hasn't migrated to use version 3 of the API yet.

**Comment by adecarolis** [comment]
Looks like I'm between a rock and a hard place

**Comment by iennae** [comment]
You can fork the cookbook for now, update to version 3 of the sdk in the metadata and see whether the resources you want to use will work. We do plan to migrate to version 3 at some point, but it's going to take a lot of testing to make sure all of the resources within the cookbook work as expected.

**Comment by adecarolis** [comment]
I was already trying to port the cookbook to v3. Right now it fails with:
```ArgumentError: aws_route53_record[default-centos-66-priv.s--e.net] (se_route53::default line 13) had an error: ArgumentError: missing required parameter params[:is_truncated]
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/param_validator.rb:32:in `validate!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:257:in `data_to_http_resp'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:242:in `http_response_stub'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:209:in `default_stub'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:197:in `block in next_stub'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.6.0/lib/aws-sdk-core/client_stubs.rb:194:in `synchronize' ```

**Comment by adecarolis** [comment]
I actually found the problem is limited to the mock parameter. I patched it and now the library seems to be fully compatible with v3

**Comment by gdavison** [comment]
I created #342, which allows the cookbook to work with either v2 or v3

**Comment by tas50** [comment]
This should be fixed now that we allow the v3 gems.

**Comment by scalp42** [comment]
@tas50 still running into this issue:

```
root@ip-10-42-207-40:~# /opt/chefdk/embedded/bin/gem list | egrep 'aws-sdk '
aws-sdk (3.0.1, 2.11.50)


Gem::ConflictError
------------------
Unable to activate aws-sdk-kms-1.5.0, because aws-sdk-core-2.11.50 conflicts with aws-sdk-core (~> 3)

```

I see we allow v2 to be installed but I'm not sure how to force v3. Any idea?
