### ISSUE TITLE
An error occurred while installing aws-sigv4 (1.0.2), and Bundler cannot continue

### ISSUE THREAD

**Issue by MarcusMaximus** [chef-cookbooks/aws#325]
### Cookbook version
cookbook 'aws', '~> 7.2.1'

### Chef-client version
[2017-10-30T23:47:09+00:00] INFO: *** Chef 12.19.36 ***

### Platform Details
Cloud Provider - AWS
31-Oct-2017 10:47:08 | DISTRIB_ID=Ubuntu
31-Oct-2017 10:47:08 | DISTRIB_RELEASE=14.04
31-Oct-2017 10:47:08 | DISTRIB_CODENAME=trusty
31-Oct-2017 10:47:08 | DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
31-Oct-2017 10:47:08 | NAME="Ubuntu"
31-Oct-2017 10:47:08 | VERSION="14.04.4 LTS, Trusty Tahr"
31-Oct-2017 10:47:08 | ID=ubuntu
31-Oct-2017 10:47:08 | ID_LIKE=debian
31-Oct-2017 10:47:08 | PRETTY_NAME="Ubuntu 14.04.4 LTS"
31-Oct-2017 10:47:08 | VERSION_ID="14.04"

### Scenario:
Use cookbook version 7.2.1 so I can make use of the named_iam_capability option to the cloudformation_stack resource. This is so  Ican assign an IAM role to my instances that get launched.

### Expected Result:
My recipes can use the latest cookbook and I can assign an IAM role to the instances it creates. 

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
31-Oct-2017 10:47:14 | [2017-10-30T23:47:14+00:00] ERROR: Running exception handlers
-- | --
31-Oct-2017 10:47:14 | [2017-10-30T23:47:14+00:00] ERROR: Exception handlers complete
31-Oct-2017 10:47:14 | [2017-10-30T23:47:14+00:00] FATAL: Stacktrace dumped to /home/bamboo/.chef/cache/chef-stacktrace.out
31-Oct-2017 10:47:14 | [2017-10-30T23:47:14+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
31-Oct-2017 10:47:14 | [2017-10-30T23:47:14+00:00] ERROR: Expected process to exit with [0], but received '5'
31-Oct-2017 10:47:14 | ---- Begin output of bundle install ----
31-Oct-2017 10:47:14 | STDOUT: Fetching gem metadata from https://rubygems.org/
31-Oct-2017 10:47:14 | Fetching version metadata from https://rubygems.org/
31-Oct-2017 10:47:14 | Resolving dependencies...
31-Oct-2017 10:47:14 |  
31-Oct-2017 10:47:14 | Bundler::GemspecError: Could not read gem at /opt/chefdk/embedded/lib/ruby/gems/2.3.0/cache/aws-sigv4-1.0.2.gem. It may be corrupted.
31-Oct-2017 10:47:14 | Using jmespath 1.3.1
31-Oct-2017 10:47:14 | Using bundler 1.12.5
31-Oct-2017 10:47:14 | An error occurred while installing aws-sigv4 (1.0.2), and Bundler cannot
31-Oct-2017 10:47:14 | continue.
31-Oct-2017 10:47:14 | Make sure that `gem install aws-sigv4 -v '1.0.2'` succeeds before bundling.
31-Oct-2017 10:47:14 | STDERR: sudo: no tty present and no askpass program specified
31-Oct-2017 10:47:14 | sudo: no tty present and no askpass program specified
31-Oct-2017 10:47:14 | ---- End output of bundle install ----
31-Oct-2017 10:47:14 | Ran bundle install returned 5
31-Oct-2017 10:47:14 | [2017-10-30T23:47:14+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by tas50** [comment]
This should be fixed now that we allow the v3 gems.
