### ISSUE TITLE
How to pass variable in powershell script recipe

### ISSUE THREAD

**Issue by akashsarpate** [chef-cookbooks/aws#329]
I have recipe which is of powershell commands

powershell_script "run-isci" do
code <<-EOH
Set-Service -Name msiscsi -StartupType Automatic
Start-Service msiscsi
New-IscsiTargetPortal -TargetPortalAddress 165.xx.xx.xx
Connect-IscsiTarget -NodeAddress iqn.2015.xxxx.xx -TargetPortalAddress 165.xx.xx.xx -IsPersistent $True

EOH
end

I am getting values 165.xx.xx.xx and iqn.2015.xxxx.xx from another recipe and i wanted to pass it to this recipe.
How i can achieve this?

**Comment by cheeseplus** [comment]
For general questions about Chef, please visit our community slack channel https://community-slack.chef.io/. This issue tracker is for issues specifically with the `aws` cookbook.

To answer your question, you'd probably want to use node attributes which you could set in a recipe or in an attributes file so the recipe would look something like:
```
powershell_script "run-isci" do
code <<-EOH
Set-Service -Name msiscsi -StartupType Automatic
Start-Service msiscsi
New-IscsiTargetPortal -TargetPortalAddress #{node['iscsi']['target_address']}
Connect-IscsiTarget -NodeAddress #{node['iscsi']['node_address']} -TargetPortalAddress #{node['iscsi']['target_address']} -IsPersistent $True

EOH
end
```

**Comment by akashsarpate** [comment]
I am getting values for iscsi and target_address from different recipe, can i use these values as node attributes ?

**Comment by akashsarpate** [comment]
How i can assign values to node attributes iscsi and target_address?

**Comment by akashsarpate** [comment]
I am getting values for target_address and node_address from this recipe:

bkp_id = List_volume_attached_acd.list_volume_acd('ocid1.instance.oc1.iad.abuw')
target_address = bkp_id.map(&:ipv4)
node_address = bkp_id.map(&:iqn)

and i have to use these values in above recipe which is powershell script.

**Comment by cheeseplus** [comment]
Locking this issue as this isn't the venue to ask general Chef questions and you've already opened a Discourse thread.
