### ISSUE TITLE
Add get_parameters_by_path to SSM

### ISSUE THREAD

**Issue by dorongutman** [chef-cookbooks/aws#343]
### Scenario:
The SSM capability that was added lately for getting and setting parameters in the parameter store is missing the get_parameters_by_path method

**Comment by chefbob** [comment]
I can try and take a look.  How would you propose to use it in a Chef Cookbook?  What would you want to happen if it returned a next token because of pagination?

**Comment by dorongutman** [comment]
@chefbob thanks. Ideally, I'd like to the option to specify whether I want all parameters from all pages or a specific amount of pages (with a default of 1?).
In my specific case, I need all parameters from all pages.

**Comment by chefbob** [comment]
@dorongutman I added get_paramaters and get_parameters_by_path.  The problem is the code returns hashes and I don't know how one would retrieve the individual values from the hash.  You can see the code here, https://github.com/chefbob/aws

**Comment by chefbob** [comment]
I finally got this working and submitted a pull request.  You can view the current code here, https://github.com/chefbob/aws.

**Comment by gbish** [comment]
@chefbob Is #349 going to be sorted any time soon? I'm eager to utilise the SSM changes 😄

**Comment by chefbob** [comment]
Not sure.  @tas50, we met at ChefConf and discussed the changes I made. Is there anything else that needs to be done for [#349](https://github.com/chef-cookbooks/aws/pull/349)?

**Comment by chefbob** [comment]
This is now available in release 7.5.0
