### ISSUE TITLE
aws_ebs_volume timeout question

### ISSUE THREAD

**Issue by Gary-Armstrong** [chef-cookbooks/aws#350]
### Cookbook version
7.3.1

### Chef-client version
13.8.5

### Platform Details
AWS - CentOS 7 1801_1 Marketplace AMI

### Scenario:
I'm managing a couple EBS in this cookbook, and in other cookbooks.  The second EBS in this CB consistently times out waiting for attachment. Previous 10GB EBS works fine.  All EBS attach fine in other CBs.  I've adjusted the timeout to '600' and it still errors, though that should be plenty of time for a 50GB EBS to attach. I'm here to ask if there are any pro-tips on troubleshooting this.

### Steps to Reproduce:
I don't really know how to reproduce this but the following code consistently fails:
```
aws_ebs_volume 'ldm' do
  size 50
  device '/dev/xvdf'
  description 'LDM'
  volume_type 'gp2'
  delete_on_termination true
  timeout 600
  action [:create, :attach]
end
```
The error:
```
* aws_ebs_volume[ldm] action attach

  ================================================================================
  Error executing action `attach` on resource 'aws_ebs_volume[ldm]'
  ================================================================================

  RuntimeError
  ------------
  Timed out waiting for volume attachment after 600 seconds

  Cookbook Trace:
  ---------------
  /tmp/kitchen/cache/cookbooks/aws/resources/ebs_volume.rb:267:in `rescue in attach_volume'
  /tmp/kitchen/cache/cookbooks/aws/resources/ebs_volume.rb:245:in `attach_volume'
  /tmp/kitchen/cache/cookbooks/aws/resources/ebs_volume.rb:91:in `block (2 levels) in class_from_file'
  /tmp/kitchen/cache/cookbooks/aws/resources/ebs_volume.rb:89:in `block in class_from_file'
```
### Expected Result:
Device attachment.

### Actual Result:
See above.

**Comment by majormoses** [comment]
Could you please run an `sudo strace -p $CHEF_CLIENT_PID` while it sits there? Aside from aws being slow there could be something odd going on. I saw that when I had lots of versions of the `aws-*` gems installed on some servers at work that they ran for an incredibly long time and running an `strace` revealed that there were files being referenced in compiled gems that no longer existed. In my case I was able to do a `/opt/chefdk/embedded/bin/gem cleanup` (Which should be tested on a non production instance first) and had to reinstall `addressable` to fix ohai removed a lot of these errors. In our scenario with ssm parameters we shaved full minutes of execution. The 8.x releases pin to minor versions of specific aws gems and should hopefully reduce these kinds of situations in the future. I can't say this is the same issue yet though.

**Comment by Gary-Armstrong** [comment]
Ah, whoops, I completely forgot about this. Root cause was user error. Please ignore.

**Comment by Sangeethavisa** [comment]
@Gary-Armstrong Can you please let me know the error clearly as I'm facing the same issue now

**Comment by Gary-Armstrong** [comment]
@Sangeethavisa It has been a long time but I believe I had already attached that EBS (xvdf) in a prior chef run and the resulting error was simply a timeout, as above.
