### ISSUE TITLE
Parameter Store: get parameters by path

### ISSUE THREAD

**Issue by dsharkov** [chef-cookbooks/aws#356]
### New feature
Add ability to get all keys/values from AWS Systems Manager Parameter Store by [get-parameters-by-path](https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameters-by-path.html)
I can get keys and values by AWS CLI (i.e. all which started from my prefix and with decrypted values):
`aws ssm get-parameters-by-path --region eu-west-1 --path /my_prefix --recursive --with-decryption`

Thanks in advance!

### Expected Result:
I have aws_ssm_parameter_store resource with :get_by_path action (or any else) to get keys/values from Parameter Store.

### Actual Result:
There is no way to get keys/values from Parameter Store by path

**Comment by chefbob** [comment]
This is now available. It was merged two days ago.

**Comment by dsharkov** [comment]
Thanks in advance!
