### ISSUE TITLE
[feature-request] Upsert action for `route53_record`

### ISSUE THREAD

**Issue by amitsaha** [chef-cookbooks/aws#374]
The `aws_route53_record` currently allows creation and deletion of a record. However, a valid use case which I currently have is to update a record. For example, if my A record has two IP addresses, I may want to add/remove one/more instead of recreating the record. The [AWS API](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html)/SDK refers to this as an `upsert` operation. Would you folks be keen to accept a PR to add this to the current `route53_record` resource?

In terms of how the UI would look like, perhaps:

```
route53_record "update a record" do
  name  "test"
  value "16.8.4.2"
  type  "A"  
  zone_id "ID VALUE"
  overwrite true
  fail_on_error false
  action :upsert
end
```

**Comment by majormoses** [comment]
I have not used this but from what I can tell from a quick glance of the code it already supports that via an action of `:create`: https://github.com/chef-cookbooks/aws/blob/master/resources/route53_record.rb#L37-L39 can you try this and let me know if that works?

**Comment by amitsaha** [comment]
ah @majormoses - i will try it out, but from the code certainly looks like what I am looking for.

**Comment by amitsaha** [comment]
Thanks @majormoses - closing this.
