### ISSUE TITLE
Credentials in the ~/.aws/credentials file don't work

### ISSUE THREAD

**Issue by pschiffe** [chef-cookbooks/aws#377]
### Cookbook version
8.0.3

### Chef-client version
12.22.5

### Platform Details
Ubuntu 16.04 in Vagrant

### Scenario:
Download a file from s3 with `aws_s3_file` by using credentials in `~/.aws/credentials` file.

### Steps to Reproduce:
Resource definition looks like this:
```
aws_s3_file "#{tmpdir}/archive.tar" do
  region region
  bucket s3_bucket
  remote_path s3_key
  owner "root"
  group "root"
  mode "0600"
  action :create
end
```
Secrets file looks like this:
```
# cat /home/deploy/.aws/credentials 
[stag]
aws_access_key_id = xxx
aws_secret_access_key = yyy
region = us-east-1
aws_session_token = zzz

[prod]
aws_access_key_id = xxx
aws_secret_access_key = yyy
region = us-east-1
aws_session_token = zzz
```
I also have the following env vars set:
```
AWS_PROFILE=stag
AWS_SHARED_CREDENTIALS_FILE=/home/deploy/.aws/credentials
```
aws cli is working fine:
```
# aws sts get-caller-identity
{
    "Arn": "arn:aws:sts::xxx:assumed-role/yyy",
    "Account": "zzz",
    "UserId": "www"
}
```

### Expected Result:
It works.

### Actual Result:
```
Aws::Sigv4::Errors::MissingCredentialsError
-------------------------------------------
missing credentials, provide credentials with one of the following options:
   - :access_key_id and :secret_access_key
   - :credentials
   - :credentials_provider

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/aws/libraries/ec2.rb:97:in `create_aws_interface'
/tmp/kitchen/cache/cookbooks/aws/resources/s3_file.rb:58:in `s3'
/tmp/kitchen/cache/cookbooks/aws/resources/s3_file.rb:67:in `s3_obj'
/tmp/kitchen/cache/cookbooks/aws/resources/s3_file.rb:141:in `do_s3_file'
/tmp/kitchen/cache/cookbooks/aws/resources/s3_file.rb:36:in `block in class_from_file'

System Info:
------------
chef_version=12.22.5
platform=ubuntu
platform_version=16.04
ruby=ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
program_name=chef-client worker: ppid=1904;start=10:30:57;
executable=/opt/chef/bin/chef-client
```

**Comment by pschiffe** [comment]
Here is the debug log from chef run:
```
[2019-03-04T10:56:35+00:00] DEBUG: Initializing the S3 Object for bucket: XXX path: YYY
[2019-03-04T10:56:35+00:00] DEBUG: Initializing the S3 Client
[2019-03-04T10:56:35+00:00] DEBUG: Using local credential chain
[2019-03-04T10:56:35+00:00] DEBUG: Initializing interface with client interface options: {:region=>"eu-west-1", :http_proxy=>nil}
```

**Comment by majormoses** [comment]
I have not had much time to deep dive on this yet but I have a couple initial thoughts/questions. Does chef run as the `deploy` user? Typically chef runs as the `root` user. While its possible to change the user that chef runs as it severely limits its capabilities and therefore is not recommended. I would guess that in order to support this either the credentials need to live under the root user or we need to supply a method to tell the provider where it can retrieve those credentials. You did not indicate if this was working code and an upgrade broke this or if this is a new implementation, can you please clarify? It would be helpful in understanding if we had a regression or if this method of auth was never supported by a user other than `root`.

**Comment by pschiffe** [comment]
Hi @majormoses , thanks for taking a look. Here are answers to your questions:
* this is not a regression AFAIK, I'm trying a new setup
* chef is running as a root user, however we are changing the `HOME` env var to `/home/deploy` before downloading the file from s3
```
  ruby_block "change HOME to /home/#{app_user} for source checkout" do
    block do
      ENV['HOME'] = "/home/#{app_user}"
    end
  end
```
```
[2019-03-05T03:14:11+00:00] DEBUG: Provider for action run on resource ruby_block[change HOME to /home/deploy for source checkout] is Chef::Provider::RubyBlock
```

I've tried it with placing the `.aws` dir to both places, `/root` and `/home/deploy` but it didn't work either way. According to [1] I can set the `AWS_SHARED_CREDENTIALS_FILE` env var, but it looks like this works only for aws cli. According to [2], I don't see any mention of that env var, only that it has to be done in the code like:
```
shared_creds = Aws::SharedCredentials.new(path: 'my_path')
Aws.config.update(credentials: shared_creds)
```

[1] https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
[2] https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html#aws-ruby-sdk-credentials-shared

**Comment by pschiffe** [comment]
Hmm.. so, it's working for me now. The `AWS_PROFILE` env var wasn't properly propagated :-(
If I put the `.aws` dir inside of `/home/deploy` (b/c of the changed `HOME`) and set `AWS_PROFILE`, it's working just fine. Thank you @majormoses , your hints helped me get to this fix.

Also the `AWS_SHARED_CREDENTIALS_FILE` env var is working when I put the `.aws` dir somewhere else. Thanks!
