### ISSUE TITLE
Bump aws-sdk-core to 3.52.1

### ISSUE THREAD

**Issue by scalp42** [chef-cookbooks/aws#386]
Is there any plan to bump aws-sdk-* related gems?

Please see https://github.com/aws/aws-sdk-ruby/issues/2044 as well.

Thanks in advance

UPDATE: I'm thinking `aws-sigv4` is the culprit here.

**Comment by scalp42** [comment]
If you look at https://rubygems.org/gems/aws-sdk-autoscaling/versions/1.22.0, there's a dependency on `aws-sigv4` for 1.1 but we have `~> 1.0.3`.

**Comment by majormoses** [comment]
If you make a PR and explain if there any breaking changes I am more than happy to merge and release it.

**Comment by scalp42** [comment]
Just pushed to our environment and rolled it out. No issues on our side.

**Comment by majormoses** [comment]
https://github.com/chef-cookbooks/aws/pull/387#issuecomment-493136957

**Comment by majormoses** [comment]
I have opened https://github.com/chef-cookbooks/aws/pull/388 which will include these changes and am awaiting review for release. Thanks for your hard work.

**Comment by majormoses** [comment]
this has been released in https://supermarket.chef.io/cookbooks/aws/versions/8.0.4

**Comment by scalp42** [comment]
Thanks a lot @majormoses ❤️
