### ISSUE TITLE
aws_s3_file IAM role support

### ISSUE THREAD

**Issue by defunct73** [chef-cookbooks/aws#71]
Would it be possible to add IAM role support to the aws_s3_file provider?  It currently requires aws_access_key_id and aws_secret_access_key be set.

Thanks for consideration.

**Comment by kgf** [comment]
Hoping this will be merged soon, as we use IAM roles for all our EC2 instances.

Thanks

**Comment by ubiquitousthey** [comment]
@kgf It has been merged.  It does have an issue on non-EC2 instances.  PR #115 fixes this.

**Comment by tas50** [comment]
Closing this out since we have support for roles and the fix for non-ec2 instances has been merged
