### ISSUE TITLE
RuntimeError: Volume  no longer exists

### ISSUE THREAD

**Issue by djdjdj** [chef-cookbooks/aws#75]
Hi,
Using the aws cookbook, I am trying to create a volume and attaching it using the provider, ebs_volume.rb. While doing this, I am getting the error "Volume  no longer exists".  

[2014-06-26T07:43:17-04:00] ERROR: aws_ebs_volume[new_ebs_volume] (aws::default line 30) had an error: RuntimeError: Volume  no longer exists
[2014-06-26T07:43:17-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

The fix provided on resolved issue is already there in the provider, but not helping.
Let me know if you need any further information to resolve this.

Early help is much appreciated as I have very less time to complete this task. Thank you.

**Comment by tas50** [comment]
The backend gem has changed since this was reported and some of the ebs setup code has been ripped out.  I'm going to close this now, but feel free to open it up if you're still having the issue with version 3.2 or later of the cookbook.
