### ISSUE TITLE
Can't create a RAID on an HVM instance

### ISSUE THREAD

**Issue by aub** [chef-cookbooks/aws#80]
Per the AWS docs:

"Hardware virtual machine (HVM) AMIs (such as the base Windows and Cluster Compute images) do not support the use of trailing numbers on device names (xvd[a-p][1-15])."

The RAID recipe compiles the disk by making device names like sdi1, sdi2, etc., so I get an error like this when trying to create the RAID:

"InvalidParameterValue: Value (/dev/sdi1) for parameter device is invalid. /dev/sdi1 is not a valid EBS device name."

**Comment by tas50** [comment]
We've removed the aws_raid provider so this bug is no longer valid for this cookbook. I encourage anyone that needs the functionality to take on the provider in its own codebase. As ebs_raid itself is not a core AWS service we don't see it as fitting here.
