### ISSUE TITLE
feature request: encrypted EBS volume support

### ISSUE THREAD

**Issue by neallawson** [chef-cookbooks/aws#91]
it would be nice to set EBS volume encryption.

**Comment by bprocek** [comment]
+1...I also require this ability to satisfy various compliance requirements.

**Comment by pjungwir** [comment]
This works for me:

    aws_ebs_volume 'encrypted_ebs_volume' do
      size 100
      device '/dev/sdi'
      encrypted true
      action [:create, :attach]
      timeout 600
    end

**Comment by tas50** [comment]
Support for encrypted EBS vols is on master and will be released as 2.8.0
